In [2]:
import numpy as np

In [3]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)
print(arr * 4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(arr[np.argmin(arr)]) # smallest number
print(arr[np.argmax(arr)]) # largest number
print(np.min(arr))
print(np.max(arr)) # yes they match
print(arr[arr > 20])

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
4
50
4
50
[27 31 50 39 35]


In [4]:
matrix = [[5, 12, 17, 9],[8, 21, 14, 3],[6, 13, 19, 11]]
matrix = np.array(matrix)
print(matrix.shape) # 3 rows and 4 columns
print(matrix[:,2])
print(matrix[1])
print(matrix * 2)
print(np.mean(matrix, axis = 0))
print(np.mean(matrix))
print(np.max(matrix, axis = 1))
print(np.min(matrix, axis = 0))
flattened = matrix.flatten() # got flattened into one dimension
index_min = np.argmin(flattened)
index_max = np.argmax(flattened)
np.unravel_index(index_min, matrix.shape)
np.unravel_index(index_max, matrix.shape)
matrix[matrix > 15]
print(np.sort(matrix))

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [10]:
arr = np.array([[2, 3, 5],[14, 6, 8],[11, 13, 17],[7, 10, 13]])
def rows_prime(arr):
    def prime(num):
        if num < 2:
            return False
        for i in range(2, num):
            if num % i == 0:
                return False
        return True

    result = []
    for row in arr:
        for val in row:
            if prime(val):
                result.append(row)
    return np.array(result)

In [38]:
def checkerboard():
    board = np.zeros((8,8))
    board[::2, 1::2] = 1 
    board[1::2, ::2] = 1
    return 1 - board
def reverse_checkerboard():
    board = np.zeros((8,8))
    board[::2, 1::2] = 1 
    board[1::2, ::2] = 1
    return board

In [40]:
def expansion(string, n):
    result = []
    for word in string:
        spaces = (" " * n).join(word)
        result.append(spaces)
    return np.array(result)

In [41]:
def second_brightest(arr):
    result = []
    for row in arr:
        sorted_row = np.sort(row)
        result.append(sorted_row[-2])
    return np.array(result)